### PR TITLE
Pass full deployment spec rather than just name

### PR DESCRIPTION
**Pull request by mikkeloscar**
In #66 the deployment name was passed to `delete_deployment()` rather than the full deployment spec which caused a crash when trying to delete deployments.

This fixes the issue by first looking up the full deployment spec and passing that.

### CODE REVIEW

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
A unit test would be nice to not run into problems again :smirk:

**Comment by mikkeloscar** [comment]
@hjacobs added a test.

**Comment by hjacobs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
