### PR TITLE
#16 encrypt command

### LINKED ISSUE #16: Command to encrypt values for Kubernetes secrets
Call Autobahn Deployment API which encrypts the given value with AWS KMS (or any other service for non-AWS clusters in the future).

### PR DESCRIPTION
**Pull request by hjacobs**
Fixes #16.

IMO we should change the Deploy API to accept `plain_text` instead of `plaintext`.

### CODE REVIEW

**Comment by rafaelcaricio** [comment]
👍

**Comment by hjacobs** [comment]
@rafaelcaricio should we change the Deploy API first and update the PR? (`plaintext` -> `plain_text`)

**Comment by hjacobs** [comment]
Hmm, ok, apparently it's written as one word "plaintext" (https://en.wikipedia.org/wiki/Plaintext).

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
