### PR TITLE
render-template should have the same UI of create-deployment

### PR DESCRIPTION
**Pull request by rafaelcaricio**
I run the command:
```
$ zdeploy render-template mytemplate.yaml foobar 0.1.0 1 replicas=2
```
To check if everything is ok before doing:
```
$ zdeploy create-deployment mytemplate.yaml foobar 0.1.0 1 replicas=2
```
Same parameters just changing the subcommand.

### CODE REVIEW

**Comment by rafaelcaricio** [comment]
👍

**Comment by hjacobs** [comment]
Sorry, I'm vetoing here --- `render-template` is really a more generic approach and can be used for other templates (Cloud Formation and other Kubernetes manifests)  too.

Proposal: add a `--dry-run` option to `create-deployment` to print the rendered template (we probably can add `--dry-run` to other commands too).

**Comment by hjacobs** [comment]
:-1:

**Comment by rafaelcaricio** [comment]
@hjacobs `--dry-run` sounds good to me.

**Pull request closed without merging**
