### PR TITLE
#17 add promote-deployment command to change "stage" label

### PR DESCRIPTION
**Pull request by hjacobs**
This will not work out-of-the-box for deployments as template labels cannot be changed if the `spec/selector` is not set (thus inheriting from template labels). Also Kubernetes will delete/spawn pods when changing the label (which is kind of stupid for our use case).

### CODE REVIEW

**Comment by hjacobs** [comment]
Also see the discussion here: https://github.com/kubernetes/kubernetes/issues/26202

**Comment by rafaelcaricio** [comment]
👍

**Comment by rafaelcaricio** [comment]
👍

**Comment by hjacobs** [comment]
:+1:

**Comment by rafaelcaricio** [comment]
👍

**Comment by rafaelcaricio** [comment]
https://github.com/zalando/connexion/pull/355

**Pull request merged**
