### PR TITLE
Check if target deployment exists on switch

### PR DESCRIPTION
**Pull request by rafaelcaricio**
Verify if target deployment really exists. Avoid problems with typos.

### CODE REVIEW

**Comment by hjacobs** [comment]
Can you add a test? (we have not many yet, but we can start now :smirk:)
Thanks!

**Comment by hjacobs** [comment]
:+1:

**Comment by rafaelcaricio** [comment]
👍

**Comment by jkozlowicz** [comment]
👍

**Comment by hjacobs** [comment]
@rafaelcaricio please make your membership "public" on https://github.com/orgs/zalando/people?utf8=%E2%9C%93&query=rafaelcaricio%20

**Comment by rafaelcaricio** [comment]
👍

**Pull request merged**
